# Generated by Django 4.2.11 on 2025-10-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_author_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
